### ISSUE TITLE
更新群组成员扩展信息时收不到消息

### ISSUE THREAD

**Issue by AkazaRenn** [hexsum/Mojo-Webqq#218]
我加了一个两千人群……每次更新信息得大概一小时，然后这一小时就收不到消息也发不了消息什么操作都不能做，有什么办法么？

**Comment by sjdy521** [comment]
new里面可以设置下启动后不初始化群信息，也不定期更新群信息
Mojo::Webqq->new(is_init_group=>0,is_update_group=>0);

**Comment by AkazaDorian** [comment]
@sjdy521 可不可以设置单独某个群不更新呢？

**Comment by sjdy521** [comment]
这个更新不更新对接收好和发送消息并没有影响，如果针对特定群不更新 那你那一两千个群不是仍然要等待很长时间？

**Comment by AkazaDorian** [comment]
@sjdy521 只是我并不是很常用那个群……但是其他群还是希望能够更新的

**Comment by sjdy521** [comment]
主要还是要看你希望更新的目的是什么，因为正常的接收和发送消息都并不需要更新操作

**Comment by tusooa** [comment]
我想是不是可以考虑单分一个进程出来更新信息，这一段阻塞确实挺恼人的。

**Comment by sjdy521** [comment]
@tusooa perl的多进程模型跨平台支持不是很好，所以当初才选择了单进程异步的方式来模拟并行处理
更新群消息这个操作，代码内部实际上是有尽量按照异步非阻塞的方式取处理的，但是可能实现下有些问题，看起来还是会阻塞很长时间，暂时搞不清楚

**Comment by tusooa** [comment]
https://github.com/sjdy521/Mojo-Webqq/blob/bebbf25341c66c30d54c26da8fc13c01687897a7/lib/Mojo/Webqq/Model.pm#L627
这条是不是应该用Queue来实现（上一个群抓完了开始抓下一个）而不是延时执行。。。
另外，瓶颈是网络请求部分吧？

**Comment by sjdy521** [comment]
这里的timer只是把请求的开始时间给分散了，网络请求的部分都是异步非阻塞的
