### ISSUE TITLE
【置顶】WebQQ即将关闭

### ISSUE THREAD

**Issue by Zxilly** [hexsum/Mojo-Webqq#281]
由于业务调整，webQQ即将在2019年1月1日停止服务。请到im.qq.com下载QQ客户端使用，感谢你对QQ的支持。
https://web2.qq.com

**Comment by doukai** [comment]
唉，估计一堆基于webqq的开源项目就此告别了

**Comment by goodtogood** [comment]
可惜了

**Comment by tetsaicn** [comment]
GG

**Comment by sjdy521** [comment]
webQQ即将在2019年1月1日停止服务，本项目也目前也决定停止维护，感谢大家三年来的一路陪伴

**Comment by Edlen-xulun** [comment]
QQ机器人要退役了

**Comment by w7374520** [comment]
感谢！！！

**Comment by li2go** [comment]
太遗憾了，今天才看到这个这么优秀的项目。

过来上柱香，，


🕯️

**Comment by Evlos** [comment]
辛苦了，谢谢

**Comment by linfree** [comment]
坚持这么久，不容易。
谢谢~

**Comment by MartisW** [comment]
感谢

**Comment by onewesong** [comment]
好像还能用？

**Comment by LukeDev2K** [comment]
有其他协议的吗

**Comment by falconshark** [comment]
現在的QQ機器人好像就只有非開源方案的酷Q了，採用Android協議所以到現在還沒有倒。
https://cqp.cc/
免費版可以玩玩。
